### ISSUE TITLE
Saiku Chart Plus is working on standalone Saiku server ?

### ISSUE THREAD

**Issue by mrhaiem** [it4biz/SaikuChartPlus#3]
Hello,

I would like to thank you for the great job perform !! 

Is it possible to install your plugin without pentaho by follow the recommendation hereafter ? 

Thanks in advance for your feedback.

BEst Regards

Mehdi

For developer or advanced instalation
1) Edit the file saiku/ui/index.html, insert the code below:

<script type="text/javascript" src="js/saiku/plugins/Chart/plugin.js" defer></script>
        

<script type="text/javascript" src="js/saiku/plugins/SaikuChartPlus/plugin.js" defer></script>

<script type="text/javascript" src="https://www.google.com/jsapi"></script>

<script type="text/javascript"> 
     google.load('visualization', '1.0', {'packages':['geochart']});
</script>

**Comment by emawings** [comment]
Hello everyone

Can the Chart Plus  pluggin visualise into maps  queries of spatial dimensions stocked in a datawarehouse such as Postgis?

Thank you in advance!

**Comment by fernandommota** [comment]
Hello @emawings,

If you want use latitude and longitude points for now this is not possible.

Regards
