### ISSUE TITLE
Error ocurred when installing pluging Saiku Chart Plus

### ISSUE THREAD

**Issue by angelchate** [it4biz/SaikuChartPlus#36]
When you install the pluging Saiku Chart Plus within the platform pentaho, me this error message appears. I'm using version 6 of Pentaho Comminity.
I am attaching the log file.
Thank you very much.
Angel

[logs.docx](https://github.com/it4biz/SaikuChartPlus/files/277933/logs.docx)

**Comment by caiomsouza** [comment]
When did you test it?
I tried now and it is okay.
Could you try again?

**Comment by angelchate** [comment]
I went to install the plugin and is now perfect.
This s due to the version of Pentaho?
Thank you very much.
Angel

2016-05-23 12:51 GMT-05:00 Caio Moreno de Souza notifications@github.com:
