### ISSUE TITLE
Insert Colombian Map in Saiku Chart Plus

### ISSUE THREAD

**Issue by ghost** [it4biz/SaikuChartPlus#5]
Estamos trabalhando com a ferramenta saiku-chart-plus e usamos GeoMaps, mas só aparece os países mas nao as ciudades. Como eu faz para mostrar as Cidades na Colombia? 

Muito Obrigado.

**Comment by asgarcez** [comment]
Estou com o mesmo problema quando aos municípios de Mato Grosso - Brasil. Como faço para gerar o Geochart deles?

Obrigado.
